package fr.formation.inti.entities;
// Generated 10 avr. 2019 09:24:27 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Annonces generated by hbm2java
 */
@Entity
@Table(name = "annonces", catalog = "projet")
public class Annonces implements java.io.Serializable {

	private int idAnnonces;
	private Transactions transactions;
	private Utilisateurs utilisateurs;
	private String description;
	private String photo;
	private int prix;
	private Date date;
	private String adresse;
	private String titre;
	private Set<MotsClefs> motsClefses = new HashSet<MotsClefs>(0);

	public Annonces() {
	}

	public Annonces(int idAnnonces, Transactions transactions, Utilisateurs utilisateurs, String description, int prix,
			Date date, String adresse, String titre) {
		this.idAnnonces = idAnnonces;
		this.transactions = transactions;
		this.utilisateurs = utilisateurs;
		this.description = description;
		this.prix = prix;
		this.date = date;
		this.adresse = adresse;
		this.titre = titre;
	}

	public Annonces(int idAnnonces, Transactions transactions, Utilisateurs utilisateurs, String description,
			String photo, int prix, Date date, String adresse, String titre, Set<MotsClefs> motsClefses) {
		this.idAnnonces = idAnnonces;
		this.transactions = transactions;
		this.utilisateurs = utilisateurs;
		this.description = description;
		this.photo = photo;
		this.prix = prix;
		this.date = date;
		this.adresse = adresse;
		this.titre = titre;
		this.motsClefses = motsClefses;
	}

	@Id

	@Column(name = "idAnnonces", unique = true, nullable = false)
	public int getIdAnnonces() {
		return this.idAnnonces;
	}

	public void setIdAnnonces(int idAnnonces) {
		this.idAnnonces = idAnnonces;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Transactions_idTransactions", nullable = false)
	public Transactions getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Transactions transactions) {
		this.transactions = transactions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Utilisateurs_idUtilisateurs", nullable = false)
	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@Column(name = "Description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Photo", length = 45)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "Prix", nullable = false)
	public int getPrix() {
		return this.prix;
	}

	public void setPrix(int prix) {
		this.prix = prix;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Adresse", nullable = false, length = 45)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "Titre", nullable = false, length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "annonces_has_mots-clefs", catalog = "projet", joinColumns = {
			@JoinColumn(name = "Annonces_idAnnonces", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Mots-clefs_idMotClef", updatable = false) })
	public Set<MotsClefs> getMotsClefses() {
		return this.motsClefses;
	}

	public void setMotsClefses(Set<MotsClefs> motsClefses) {
		this.motsClefses = motsClefses;
	}

}
