package fr.formation.inti.entities;
// Generated 10 avr. 2019 09:24:27 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Messageries generated by hbm2java
 */
@Entity
@Table(name = "messageries", catalog = "projet")
public class Messageries implements java.io.Serializable {

	private int idMessageries;
	private Utilisateurs utilisateurs;
	private Set<Messages> messageses = new HashSet<Messages>(0);

	public Messageries() {
	}

	public Messageries(int idMessageries, Utilisateurs utilisateurs) {
		this.idMessageries = idMessageries;
		this.utilisateurs = utilisateurs;
	}

	public Messageries(int idMessageries, Utilisateurs utilisateurs, Set<Messages> messageses) {
		this.idMessageries = idMessageries;
		this.utilisateurs = utilisateurs;
		this.messageses = messageses;
	}

	@Id

	@Column(name = "idMessageries", unique = true, nullable = false)
	public int getIdMessageries() {
		return this.idMessageries;
	}

	public void setIdMessageries(int idMessageries) {
		this.idMessageries = idMessageries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Utilisateurs_idUtilisateurs", nullable = false)
	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "messageries")
	public Set<Messages> getMessageses() {
		return this.messageses;
	}

	public void setMessageses(Set<Messages> messageses) {
		this.messageses = messageses;
	}

}
