package fr.formation.inti.entities;
// Generated 10 avr. 2019 09:24:27 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name = "messages", catalog = "projet")
public class Messages implements java.io.Serializable {

	private int idMessages;
	private Messageries messageries;
	private String titre;
	private Date date;
	private String texte;

	public Messages() {
	}

	public Messages(int idMessages, Messageries messageries, String titre, Date date, String texte) {
		this.idMessages = idMessages;
		this.messageries = messageries;
		this.titre = titre;
		this.date = date;
		this.texte = texte;
	}

	@Id

	@Column(name = "idMessages", unique = true, nullable = false)
	public int getIdMessages() {
		return this.idMessages;
	}

	public void setIdMessages(int idMessages) {
		this.idMessages = idMessages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Messageries_idMessageries", nullable = false)
	public Messageries getMessageries() {
		return this.messageries;
	}

	public void setMessageries(Messageries messageries) {
		this.messageries = messageries;
	}

	@Column(name = "Titre", nullable = false, length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Texte", nullable = false, length = 65535)
	public String getTexte() {
		return this.texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

}
