package fr.formation.inti.entities;
// Generated 10 avr. 2019 09:24:27 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateurs generated by hbm2java
 */
@Entity
@Table(name = "utilisateurs", catalog = "projet")
public class Utilisateurs implements java.io.Serializable {

	private Integer idUtilisateurs;
	private String nom;
	private String prénom;
	private Date dateNaissance;
	private int codePostal;
	private String login;
	private int password;
	private String mail;
	private Set<Alerte> alertes = new HashSet<Alerte>(0);
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);
	private Set<Annonces> annonceses = new HashSet<Annonces>(0);
	private Set<Messageries> messagerieses = new HashSet<Messageries>(0);

	public Utilisateurs() {
	}

	public Utilisateurs(String nom, String prénom, Date dateNaissance, int codePostal, String login, int password,
			String mail) {
		this.nom = nom;
		this.prénom = prénom;
		this.dateNaissance = dateNaissance;
		this.codePostal = codePostal;
		this.login = login;
		this.password = password;
		this.mail = mail;
	}

	public Utilisateurs(String nom, String prénom, Date dateNaissance, int codePostal, String login, int password,
			String mail, Set<Alerte> alertes, Set<Transactions> transactionses, Set<Annonces> annonceses,
			Set<Messageries> messagerieses) {
		this.nom = nom;
		this.prénom = prénom;
		this.dateNaissance = dateNaissance;
		this.codePostal = codePostal;
		this.login = login;
		this.password = password;
		this.mail = mail;
		this.alertes = alertes;
		this.transactionses = transactionses;
		this.annonceses = annonceses;
		this.messagerieses = messagerieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUtilisateurs", unique = true, nullable = false)
	public Integer getIdUtilisateurs() {
		return this.idUtilisateurs;
	}

	public void setIdUtilisateurs(Integer idUtilisateurs) {
		this.idUtilisateurs = idUtilisateurs;
	}

	@Column(name = "Nom", nullable = false, length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prénom", nullable = false, length = 45)
	public String getPrénom() {
		return this.prénom;
	}

	public void setPrénom(String prénom) {
		this.prénom = prénom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateNaissance", nullable = false, length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "Code Postal", nullable = false)
	public int getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(int codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "Login", nullable = false, length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "Password", nullable = false)
	public int getPassword() {
		return this.password;
	}

	public void setPassword(int password) {
		this.password = password;
	}

	@Column(name = "Mail", nullable = false, length = 45)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateurs")
	public Set<Alerte> getAlertes() {
		return this.alertes;
	}

	public void setAlertes(Set<Alerte> alertes) {
		this.alertes = alertes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateurs")
	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateurs")
	public Set<Annonces> getAnnonceses() {
		return this.annonceses;
	}

	public void setAnnonceses(Set<Annonces> annonceses) {
		this.annonceses = annonceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateurs")
	public Set<Messageries> getMessagerieses() {
		return this.messagerieses;
	}

	public void setMessagerieses(Set<Messageries> messagerieses) {
		this.messagerieses = messagerieses;
	}

}
