package fr.formation.inti.entities;
// Generated 8 avr. 2019 14:51:15 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Esclaves generated by hbm2java
 */
@Entity
@Table(name = "esclaves", catalog = "bd2")
public class Esclaves implements java.io.Serializable {

	private int idEsclaves;
	private Set<Maitres> maitreses = new HashSet<Maitres>(0);
	private Set<Maitres> maitreses_1 = new HashSet<Maitres>(0);

	public Esclaves() {
	}

	public Esclaves(int idEsclaves) {
		this.idEsclaves = idEsclaves;
	}

	public Esclaves(int idEsclaves, Set<Maitres> maitreses, Set<Maitres> maitreses_1) {
		this.idEsclaves = idEsclaves;
		this.maitreses = maitreses;
		this.maitreses_1 = maitreses_1;
	}

	@Id

	@Column(name = "idEsclaves", unique = true, nullable = false)
	public int getIdEsclaves() {
		return this.idEsclaves;
	}

	public void setIdEsclaves(int idEsclaves) {
		this.idEsclaves = idEsclaves;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "maitres_has_esclaves", catalog = "bd2", joinColumns = {
			@JoinColumn(name = "Esclaves_idEsclaves", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Maitres_idMaitres", nullable = false, updatable = false) })
	public Set<Maitres> getMaitreses() {
		return this.maitreses;
	}

	public void setMaitreses(Set<Maitres> maitreses) {
		this.maitreses = maitreses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "esclaves")
	public Set<Maitres> getMaitreses_1() {
		return this.maitreses_1;
	}

	public void setMaitreses_1(Set<Maitres> maitreses_1) {
		this.maitreses_1 = maitreses_1;
	}

}
