package fr.formation.inti.entities;
// Generated 8 avr. 2019 14:51:15 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Maitres generated by hbm2java
 */
@Entity
@Table(name = "maitres", catalog = "bd2")
public class Maitres implements java.io.Serializable {

	private int idMaitres;
	private Esclaves esclaves;
	private Set<Esclaves> esclaveses = new HashSet<Esclaves>(0);

	public Maitres() {
	}

	public Maitres(int idMaitres, Esclaves esclaves) {
		this.idMaitres = idMaitres;
		this.esclaves = esclaves;
	}

	public Maitres(int idMaitres, Esclaves esclaves, Set<Esclaves> esclaveses) {
		this.idMaitres = idMaitres;
		this.esclaves = esclaves;
		this.esclaveses = esclaveses;
	}

	@Id

	@Column(name = "idMaitres", unique = true, nullable = false)
	public int getIdMaitres() {
		return this.idMaitres;
	}

	public void setIdMaitres(int idMaitres) {
		this.idMaitres = idMaitres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Esclaves_idEsclaves", nullable = false)
	public Esclaves getEsclaves() {
		return this.esclaves;
	}

	public void setEsclaves(Esclaves esclaves) {
		this.esclaves = esclaves;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "maitres_has_esclaves", catalog = "bd2", joinColumns = {
			@JoinColumn(name = "Maitres_idMaitres", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Esclaves_idEsclaves", nullable = false, updatable = false) })
	public Set<Esclaves> getEsclaveses() {
		return this.esclaveses;
	}

	public void setEsclaveses(Set<Esclaves> esclaveses) {
		this.esclaveses = esclaveses;
	}

}
