package fr.formation.inti.entities;
// Generated 8 avr. 2019 14:51:15 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SalaryGrade generated by hbm2java
 */
@Entity
@Table(name = "salary_grade", catalog = "bd2")
public class SalaryGrade implements java.io.Serializable {

	private int grade;
	private float highSalary;
	private float lowSalary;

	public SalaryGrade() {
	}

	public SalaryGrade(int grade, float highSalary, float lowSalary) {
		this.grade = grade;
		this.highSalary = highSalary;
		this.lowSalary = lowSalary;
	}

	@Id

	@Column(name = "GRADE", unique = true, nullable = false)
	public int getGrade() {
		return this.grade;
	}

	public void setGrade(int grade) {
		this.grade = grade;
	}

	@Column(name = "HIGH_SALARY", nullable = false, precision = 12, scale = 0)
	public float getHighSalary() {
		return this.highSalary;
	}

	public void setHighSalary(float highSalary) {
		this.highSalary = highSalary;
	}

	@Column(name = "LOW_SALARY", nullable = false, precision = 12, scale = 0)
	public float getLowSalary() {
		return this.lowSalary;
	}

	public void setLowSalary(float lowSalary) {
		this.lowSalary = lowSalary;
	}

}
